title: My amazing course
description: A very romantic sexual intercourse with the girl I had waited for 33 years.
template:
  repo: my-amazing-course-template
  name: my-amazing-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
